left_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: left_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
right_wheel_joint:
  type: effort_controllers/JointPositionController
  joint: right_wheel_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

